// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using spellbook_backend.Data;

#nullable disable

namespace spellbook_backend.Migrations
{
    [DbContext(typeof(SpellbookContext))]
    [Migration("20260213075351_MaterialsPropertyAdded")]
    partial class MaterialsPropertyAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("spellbook_backend.Models.ClassSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SpellId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassName");

                    b.HasIndex("SpellId");

                    b.HasIndex("ClassName", "Rating");

                    b.ToTable("ClassSpells");
                });

            modelBuilder.Entity("spellbook_backend.Models.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchoolOfMagic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("SpellLists")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("spellbook_backend.Models.ClassSpell", b =>
                {
                    b.HasOne("spellbook_backend.Models.Spell", null)
                        .WithMany("ClassSpells")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("spellbook_backend.Models.Spell", b =>
                {
                    b.OwnsOne("spellbook_backend.Models.SpellMetaData", "MetaData", b1 =>
                        {
                            b1.Property<int>("SpellId")
                                .HasColumnType("integer");

                            b1.PrimitiveCollection<string[]>("Ability")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.PrimitiveCollection<string[]>("ActionType")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.PrimitiveCollection<string[]>("AttackType")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<int?>("AverageDamage")
                                .HasColumnType("integer");

                            b1.Property<int>("CastingTime")
                                .HasColumnType("integer");

                            b1.PrimitiveCollection<string[]>("Components")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.PrimitiveCollection<string[]>("Conditions")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.PrimitiveCollection<string[]>("DamageDie")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.PrimitiveCollection<string[]>("DamageType")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<int>("Duration")
                                .HasColumnType("integer");

                            b1.Property<string>("Materials")
                                .HasColumnType("text");

                            b1.Property<int>("Range")
                                .HasColumnType("integer");

                            b1.PrimitiveCollection<string[]>("RollType")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.PrimitiveCollection<string[]>("TargetRelationship")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<int?>("Targets")
                                .HasColumnType("integer");

                            b1.HasKey("SpellId");

                            b1.ToTable("Spells");

                            b1.ToJson("MetaData");

                            b1.WithOwner()
                                .HasForeignKey("SpellId");
                        });

                    b.Navigation("MetaData")
                        .IsRequired();
                });

            modelBuilder.Entity("spellbook_backend.Models.Spell", b =>
                {
                    b.Navigation("ClassSpells");
                });
#pragma warning restore 612, 618
        }
    }
}
